spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.22.70.68:1521:orcl
    username: cfps7_cgo_test
    password: cargo
#配置mybatis
mybatis-plus:
  #别名包,实体类的路径
  type-aliases-package: com.example.mybatisplus.entity
  #将所有的映射文件全部加载
  mapper-locations: classpath:/mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true